{% set name = "grin" %}
{% set version = "1.3.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a8e5a1cc9461322be76cee9bd91fd546d64bbb2fd78dce8acaea9c424ade0db2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_value }}

build:
  number: 4
  skip: True  # [py3k]
  entry_points:
    - grin = grin:grin_main
    - grind = grin:grind_main
  script:
    - pip install --no-deps .

requirements:
  host:
    - python
    - pip 
  run:
    - python

test:
  commands:
    - grin -h
    - grind -h
  imports:
    - grin

about:
  home: http://pypi.python.org/pypi/grin
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Enhanced grep-like tool
  description: |
    Grin is Robert Kern's enhanced grep-like tool analagous to ack(-grep)
    (perl), rak (ruby), and ag (C).
  doc_url: https://pypi.python.org/pypi/grin
  doc_source_url: https://github.com/rkern/grin/blob/master/README.rst
  dev_url: https://github.com/rkern/grin

extra:
  recipe-maintainers:
    - nehaljwani
