travis:
  secure:
    BINSTAR_TOKEN: n8XcWLsyHoocTKy8+iIF6d/PIXcODhy0l9hcecvDNP7NJeGqN8rMboFM7e0fHvFQY4PrSdVzMkmP8UjeXYtzOTjXdurt4naEnXMgl0nvKnCQtdfgtgs/Qe9086E0KsU5lDW3+ovG57PNGeA+G7uMJCQZSThUY3EO6TcIXwt/C0Gw1JK4UBsz9SyE3cLrcukCWBHS0lpx+vB46CUDhhi2bJPXBi6Xo36GEoVC4GUj+jQEMeKukVjVhtDGkTNulwBrbS66kKQLx4NyjTX+8NmxKyRqsoAx3Meo/WJ7na/w05OGCDsx/O2JYoddCPP/YN64FBaK7kM4bc+BQw9Rq9hnmrsxL2QecnKK94vwBy+FZrS7vX8WMM+fHEIXIvWSc1S7Yt0mVh+6qAxpLY199koJhmEwkqP+yCtTJWUrdJ9xlVGZ5e70Le6QgyZLXTXa5nQ5L9hctHFhronaHNYXSldmN09qSON9BSgPEE/XYa6mXPPurn/gLSNjXrxkqQNIFRW9peu6JXyyjPFx9syWjGnmlzxm41wfsJFd2YtRjBrwEqe/6HIKz87wBBTY29TskJOqNIZ838zu9Ng1DxPXzjrpwaNyZkiCy5GXKNH63XO83gy5uaJP6TE7QRQ518x5p0+bKzlbBXUgQhcuMnBaRiHJeCvN88ROldHb7ElGKY419u4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
